services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
      MAILER_DSN: "smtp://mailer:1025"
      GITHUB_APP_ID: "2860467"
      GITHUB_WEBHOOK_SECRET: "symfony-ai-pr-reviewer-bot-12345"
      GITHUB_PRIVATE_KEY_PATH: "/app/var/github-app.pem"
      GITHUB_OAUTH_CLIENT_ID: "Ov23liDLvehNpHVw89EG"
      GITHUB_OAUTH_CLIENT_SECRET: "4d952dd729ee0d6352596b372b77c8849d8f1cc6"
      FRONT_URL: "http://localhost:5173"
    volumes:
      - ./api:/app
      - api_vendor:/app/vendor
      - ./api/secrets/symfony-ai-pr-reviewer-bot.2026-02-13.private-key.pem:/app/var/github-app.pem:ro
    depends_on:
      database:
        condition: service_healthy
      mailer:
        condition: service_started

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "!ChangeMe!"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

  csfixer:
    image: cytopia/php-cs-fixer:latest
    working_dir: /workdir
    volumes:
      - ./:/workdir

volumes:
  database_data:
  api_vendor:
