<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260315000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add processed_webhook_delivery table for idempotent webhook handling';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE processed_webhook_delivery (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, delivery_id VARCHAR(255) NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WEBHOOK_DELIVERY_ID ON processed_webhook_delivery (delivery_id)');
        $this->addSql('COMMENT ON COLUMN processed_webhook_delivery.processed_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE processed_webhook_delivery');
    }
}
