<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260228210356 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE github_installation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, installation_id INT NOT NULL, account_login VARCHAR(255) DEFAULT NULL, account_type VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT UNIQ_25806A745A63BEA7 UNIQUE (installation_id))');
        $this->addSql('CREATE TABLE user_github_installation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, app_user_id INT NOT NULL, installation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_82A2FD9A4A3353D8 ON user_github_installation (app_user_id)');
        $this->addSql('CREATE INDEX IDX_82A2FD9A167B88B4 ON user_github_installation (installation_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_github_installation_pair ON user_github_installation (app_user_id, installation_id)');
        $this->addSql('ALTER TABLE user_github_installation ADD CONSTRAINT FK_82A2FD9A4A3353D8 FOREIGN KEY (app_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_github_installation ADD CONSTRAINT FK_82A2FD9A167B88B4 FOREIGN KEY (installation_id) REFERENCES github_installation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_github_installation DROP CONSTRAINT FK_82A2FD9A4A3353D8');
        $this->addSql('ALTER TABLE user_github_installation DROP CONSTRAINT FK_82A2FD9A167B88B4');
        $this->addSql('DROP TABLE github_installation');
        $this->addSql('DROP TABLE user_github_installation');
    }
}
