# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    github.app_id: '%env(GITHUB_APP_ID)%'
    github.webhook_secret: '%env(GITHUB_WEBHOOK_SECRET)%'
    github.private_key_path: '%env(GITHUB_PRIVATE_KEY_PATH)%'
    pr_alert.from_email: '%env(PR_ALERT_FROM_EMAIL)%'
    pr_alert.from_name: '%env(PR_ALERT_FROM_NAME)%'
    pr_alert.reply_to: '%env(PR_ALERT_REPLY_TO)%'
    pr_alert.front_url: '%env(PR_ALERT_FRONT_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
